package active

import (
	"context"
	"crypto/tls"
	"fmt"
	"io"
	"net/http"
	"strings"
	"sync"
	"time"
)

// WAFResult holds WAF detection findings
type WAFResult struct {
	Subdomain string `json:"subdomain"`
	WAF       string `json:"waf"`
	Evidence  string `json:"evidence"`
}

type wafSignature struct {
	Name    string
	Headers map[string]string // header -> substring match
	Body    []string          // body substring matches
}

var wafSignatures = []wafSignature{
	{
		Name: "Cloudflare",
		Headers: map[string]string{
			"Server":    "cloudflare",
			"Cf-Ray":    "",
			"Cf-Cache-Status": "",
		},
	},
	{
		Name: "AWS WAF / CloudFront",
		Headers: map[string]string{
			"X-Amz-Cf-Id":   "",
			"X-Amz-Cf-Pop":  "",
			"X-Cache":       "cloudfront",
		},
	},
	{
		Name: "Akamai",
		Headers: map[string]string{
			"X-Akamai-Transformed": "",
			"Server":               "AkamaiGHost",
		},
	},
	{
		Name: "Sucuri",
		Headers: map[string]string{
			"X-Sucuri-ID":   "",
			"Server":        "Sucuri",
			"X-Sucuri-Cache": "",
		},
	},
	{
		Name: "Imperva / Incapsula",
		Headers: map[string]string{
			"X-CDN":     "Incapsula",
			"X-Iinfo":   "",
		},
		Body: []string{"Incapsula incident ID"},
	},
	{
		Name: "ModSecurity",
		Headers: map[string]string{
			"Server": "ModSecurity",
		},
		Body: []string{"ModSecurity", "This error was generated by Mod_Security"},
	},
	{
		Name: "F5 BIG-IP",
		Headers: map[string]string{
			"Server":           "BigIP",
			"X-Cnection":      "",
			"X-WA-Info":       "",
		},
	},
	{
		Name: "Barracuda",
		Headers: map[string]string{
			"Server": "Barracuda",
		},
		Body: []string{"Barracuda"},
	},
	{
		Name: "Fortinet / FortiWeb",
		Headers: map[string]string{
			"Server": "FortiWeb",
		},
	},
	{
		Name: "DenyAll",
		Headers: map[string]string{
			"Server": "DenyAll",
		},
	},
	{
		Name: "Wallarm",
		Headers: map[string]string{
			"Server": "nginx-wallarm",
		},
	},
	{
		Name: "Citrix NetScaler / AppFirewall",
		Headers: map[string]string{
			"Via":              "NS-CACHE",
			"Cneonction":      "",
			"X-NSProtect":     "",
		},
	},
	{
		Name: "StackPath",
		Headers: map[string]string{
			"X-SP-URL":    "",
			"X-SP-WC":     "",
		},
	},
	{
		Name: "DOSarrest",
		Headers: map[string]string{
			"Server":         "DOSarrest",
			"X-DIS-Request-ID": "",
		},
	},
	{
		Name: "Reblaze",
		Headers: map[string]string{
			"Server": "Reblaze Secure Web Gateway",
		},
	},
}

// DetectWAF checks subdomains for WAF presence
func DetectWAF(ctx context.Context, subdomains []string, threads int) <-chan WAFResult {
	results := make(chan WAFResult)
	jobs := make(chan string, len(subdomains))

	client := &http.Client{
		Transport: &http.Transport{
			TLSClientConfig: &tls.Config{InsecureSkipVerify: true},
		},
		Timeout: 8 * time.Second,
		CheckRedirect: func(req *http.Request, via []*http.Request) error {
			if len(via) >= 2 {
				return http.ErrUseLastResponse
			}
			return nil
		},
	}

	var wg sync.WaitGroup

	for i := 0; i < threads; i++ {
		wg.Add(1)
		go func() {
			defer wg.Done()
			for sub := range jobs {
				if result := detectSingle(ctx, client, sub); result != nil {
					results <- *result
				}
			}
		}()
	}

	go func() {
		for _, sub := range subdomains {
			jobs <- sub
		}
		close(jobs)
	}()

	go func() {
		wg.Wait()
		close(results)
	}()

	return results
}

func detectSingle(ctx context.Context, client *http.Client, subdomain string) *WAFResult {
	urls := []string{
		fmt.Sprintf("https://%s", subdomain),
		fmt.Sprintf("http://%s", subdomain),
	}

	for _, u := range urls {
		// Normal request
		req, err := http.NewRequestWithContext(ctx, "GET", u, nil)
		if err != nil {
			continue
		}
		req.Header.Set("User-Agent", "did_finder/2.0")

		resp, err := client.Do(req)
		if err != nil {
			continue
		}

		body, _ := io.ReadAll(io.LimitReader(resp.Body, 50*1024))
		resp.Body.Close()
		bodyStr := string(body)

		for _, sig := range wafSignatures {
			if matchWAF(sig, resp.Header, bodyStr) {
				evidence := buildEvidence(sig, resp.Header, bodyStr)
				return &WAFResult{
					Subdomain: subdomain,
					WAF:       sig.Name,
					Evidence:  evidence,
				}
			}
		}

		// Also try with a malicious-looking request to trigger WAF blocks
		maliciousURL := u + "/?id=1' OR 1=1--&<script>alert(1)</script>&cmd=cat%20/etc/passwd"
		req2, err := http.NewRequestWithContext(ctx, "GET", maliciousURL, nil)
		if err != nil {
			continue
		}
		req2.Header.Set("User-Agent", "did_finder/2.0")

		resp2, err := client.Do(req2)
		if err != nil {
			continue
		}

		body2, _ := io.ReadAll(io.LimitReader(resp2.Body, 50*1024))
		resp2.Body.Close()
		bodyStr2 := string(body2)

		for _, sig := range wafSignatures {
			if matchWAF(sig, resp2.Header, bodyStr2) {
				evidence := buildEvidence(sig, resp2.Header, bodyStr2)
				return &WAFResult{
					Subdomain: subdomain,
					WAF:       sig.Name,
					Evidence:  evidence,
				}
			}
		}

		// Check for generic WAF indicators in the malicious response
		if resp2.StatusCode == 403 || resp2.StatusCode == 406 || resp2.StatusCode == 429 || resp2.StatusCode == 501 {
			if strings.Contains(bodyStr2, "blocked") || strings.Contains(bodyStr2, "denied") ||
				strings.Contains(bodyStr2, "forbidden") || strings.Contains(bodyStr2, "firewall") {
				return &WAFResult{
					Subdomain: subdomain,
					WAF:       "Unknown WAF",
					Evidence:  fmt.Sprintf("HTTP %d with blocking keywords", resp2.StatusCode),
				}
			}
		}

		break
	}

	return nil
}

func matchWAF(sig wafSignature, headers http.Header, body string) bool {
	for header, match := range sig.Headers {
		val := headers.Get(header)
		if val != "" {
			if match == "" || strings.Contains(strings.ToLower(val), strings.ToLower(match)) {
				return true
			}
		}
	}

	bodyLower := strings.ToLower(body)
	for _, pattern := range sig.Body {
		if strings.Contains(bodyLower, strings.ToLower(pattern)) {
			return true
		}
	}

	return false
}

func buildEvidence(sig wafSignature, headers http.Header, body string) string {
	var parts []string

	for header, match := range sig.Headers {
		val := headers.Get(header)
		if val != "" {
			if match == "" || strings.Contains(strings.ToLower(val), strings.ToLower(match)) {
				parts = append(parts, fmt.Sprintf("%s: %s", header, val))
			}
		}
	}

	bodyLower := strings.ToLower(body)
	for _, pattern := range sig.Body {
		if strings.Contains(bodyLower, strings.ToLower(pattern)) {
			parts = append(parts, fmt.Sprintf("body contains '%s'", pattern))
		}
	}

	if len(parts) > 0 {
		return strings.Join(parts, "; ")
	}
	return "signature match"
}
